### ISSUE TITLE
Subscriber spans are missing topic name

### ISSUE THREAD

**Issue by kirpichenko** [mdovhopo/opentelemetry-instrumentation-pubsub#2]
Hi. We just recently added pubsub instrumentation to our Node.js applications. There is an issue with subscriber spans. They seem missing the topic name (topic.name attribute is always unknown). I checked the [code](https://github.com/mdovhopo/opentelemetry-instrumentation-pubsub/blob/4640e32e86b9addae51484ea40d50d67df553dd9/src/instrumentation.ts#L80) and found that it's taken from subscription metadata. Any ideas why it could be missing? Also, subscription name in attributes would be extremely helpful.

**Comment by mdovhopo** [comment]
Hey, thanks for your feedback, i've added (with latest release - v1.3.0) `subscription.name` as attribute to span (when it is available) also added better way of getting topic name. I will close this issue, reopen it in case of a problem. Have a nice day 🙂

**Comment by kirpichenko** [comment]
Works perfectly 👍. Thanks a lot
